### ISSUE TITLE
Telegraher2 долгие загрузки вложений 

### ISSUE THREAD

**Issue by MelonHell** [nikitasius/Telegraher#121]
В новом релизе (8.85.43), а так же в бетах очень долго загружаются вложения, а так же бесконечно грузится отправка вложений

**Comment by nikitasius** [comment]
привет глянь как сие в новой 45 версии с разрными настройками скорости

**Comment by MelonHell** [comment]
> привет глянь как сие в новой 45 версии с разрными настройками скорости
> 

Забыл написать, проблема решилась сама собой после принудительного рестарта приложения

**Comment by nikitasius** [comment]
топчек, на новой еще можно задать быстрая сеть или медленная.
