### ISSUE TITLE
Кружочки сломались 

### ISSUE THREAD

**Issue by MelonHell** [nikitasius/Telegraher#152]
При отправке кружочка, кружочек превращается в обычное видео ![1674988769414.jpg](https://user-images.githubusercontent.com/53826469/215320736-202e7105-3866-49dc-9751-e1c900090ead.jpg)

**Comment by fraylist** [comment]
В настройках телеграхер сделайте размер кружочков на 1х

**Comment by MelonHell** [comment]
> В настройках телеграхер сделайте размер кружочков на 1х

оно и так на 1х

**Comment by fraylist** [comment]
Тогда понизьте битрейт кружков

**Comment by MelonHell** [comment]
> В настройках телеграхер сделайте размер кружочков на 1х

а, всё таки 1х был битрейт, а изменение размера с 2х на 1х помогло, спасибо
