### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by AliAlmasi** [nikitasius/Telegraher#174]
![Screenshot_20231124_153943_Telegraher](https://github.com/nikitasius/Telegraher/assets/87055424/cc9e335b-fe5d-4703-b20a-a154ad25bc0c)

**Comment by yourfanboy** [comment]
telegram wont allow you to log in on version <10
current telegraher version is 9.3
feel free to fork and update this repo

**Comment by timur-g** [comment]
Duplicate od #167, you should read before posting and close this as duplicate.

**Comment by AliAlmasi** [comment]
@timur-g Thanks for the heads up, but don't you think this is too late to say? Opened in 2023 man...
