### ISSUE TITLE
Hide/mimic logged-in device name

### ISSUE THREAD

**Issue by Bugaddr** [nikitasius/Telegraher#29]
Whenever we login to new device, the tg server get to know which device we are using (in setting > privacy > devices). Is there any way that something will be implemented so that the device name can be changed/faked to diffrent device.

**Comment by Playez** [comment]
i was able to do that, do you need to spoof only device name, or app version too?

**Comment by Bugaddr** [comment]
> i was able to do that, do you need to spoof only device name, or app version too?

Being able to spoof any device identifier is cherry on the top :). Please explain how you do that.

**Comment by Playez** [comment]
> Being able to spoof any device identifier is cherry on the top :). Please explain how you do that.

I modified one file, and changed the name to 'Android unknown' and SDK to android 8.1, and when I logged in, it showed me that device 'android unknown' with android 8,1 logged in, when it actually was a xiaomi with android10, i can make a pull request with what i changed, if you need

**Comment by Bugaddr** [comment]
> > Being able to spoof any device identifier is cherry on the top :). Please explain how you do that.
> 
> I modified one file, and changed the name to 'Android unknown' and SDK to android 8.1, and when I logged in, it showed me that device 'android unknown' with android 8,1 logged in, when it actually was a xiaomi with android10, i can make a pull request with what i changed, if you need

This is a nice feature, will be waiting for your pr. Thanks :)

**Comment by Playez** [comment]
> > > Being able to spoof any device identifier is cherry on the top :). Please explain how you do that.
> > 
> > 
> > I modified one file, and changed the name to 'Android unknown' and SDK to android 8.1, and when I logged in, it showed me that device 'android unknown' with android 8,1 logged in, when it actually was a xiaomi with android10, i can make a pull request with what i changed, if you need
> 
> This is a nice feature, will be waiting for your pr. Thanks :)

#31

**Comment by Bugaddr** [comment]
Thanks for you'r efforts https://github.com/Playez i appreciate it 👍.

**Comment by nikitasius** [comment]
here is from PR, guess this way is better: 
https://github.com/nikitasius/Telegraher/pull/31#issuecomment-1079997879

**Comment by Jrchintu** [comment]
Since this issue seems to be fixed in latest commits (as a feature). I consider closing this issue. Thanks for your dedication and time.

**Comment by nikitasius** [comment]
added here 1dde8d965fd07d10157e33b2e9012a29556b4577
