### ISSUE TITLE
[FEATURE] Change Icon

### ISSUE THREAD

**Issue by SirDeveloperOrg** [nikitasius/Telegraher#35]
Hi, thanks for your hard work, just wanted say it's will be nice if you could add a feature so we can change app icon, I think the original icon don't looks nice in phone launcher.
Regards.

**Comment by nikitasius** [comment]
Hi, thanks for a kind words, i really appreciate this.
Same time, an actual icon is a part of a personality of this fork.

* Chanding the icon doesn't change the usability and it's purely cosmetic.

The actual icon have correct sizes and replaces the original TG icon.
