### ISSUE TITLE
shadow ban revamp

### ISSUE THREAD

**Issue by NSTAdventure** [nikitasius/Telegraher#61]
problem:
sometime user lazy to remember which peoplw group or channel that has been shadow banned

keep message on dm is not good idea because if we using other client msg will visible

solution:
add mark if people already shadow banned or not

add auto delete message for shadow banned people on dm only

**Comment by nikitasius** [comment]
autodeletions (the real local deletions, not just hiding) in plans, it will be part of "self moderation".

> add mark if people already shadow banned or not

it's marked in their profiles with checkbox.

**Comment by NSTAdventure** [comment]
@nikitasius yes sir 🙏

**Comment by nikitasius** [comment]
new shadowban manager have user list inside.
