### ISSUE TITLE
revamp for delete msg on dm

### ISSUE THREAD

**Issue by NSTAdventure** [nikitasius/Telegraher#62]
problem:
sometime user may want to delete a msg on dm for both user but they may forgot to check also delete for xxx
(xxx = other user on dm)

solution:
make that box checked by default

**Comment by nikitasius** [comment]
hey! done here https://github.com/nikitasius/Telegraher/commit/79afb36ada37539662dd02e43908b0ed9d997195

**Comment by nikitasius** [comment]
and here https://github.com/nikitasius/Telegraher/commit/7e5841732b3ad89c73f3e19219b923bb2026cdc9

**Comment by NSTAdventure** [comment]
> and here [7e58417](https://github.com/nikitasius/Telegraher/commit/7e5841732b3ad89c73f3e19219b923bb2026cdc9)

yes i can confirm checkbox is changed now it checked by default thank you sir
hehe 🙏😊
