### ISSUE TITLE
feature . one internal builds number

### ISSUE THREAD

**Issue by DI555** [nikitasius/Telegraher#69]
i’d like to ask a feature, it’s a one internal number for all builds.
it’s a some kind of lifehack which lets to roll back the app if you even don‘t have a root!
it will be usefull if some bugs are appeared and could be possible instal over to a prev.version of the app. in usual android os not possible to do it.
internal build number i mean in brackets - (2636704)
not descriptions - 8.74.4 , for example..

as it became now in 7 digits, i would suggest, for example, 3333333 number.
and also, to clear see connections with tg numbers, i would suggest to write descriptions - just addind a dot or dash with number!

versions could be the way like:
8.7.4.5 (3333333)
8.7.4.6 (3333333)
8.7.4.7 (3333333)

or

8.7.4-5 (3333333)
8.7.4-6 (3333333)
8.7.4-7 (3333333)

**Comment by nikitasius** [comment]
hi, version is 3 numbers (it's classic).

actually `8.74.6` mean "release 6, based on 8.7.4".

The code version now `2636006` , is mean 2636 0 06 where 2636 is vanilla code version, and 06 is the release one.
Because 2636 & arch value (added in gradle) user in API i do not touch firsh five digits, so i use two latests for release 1..99.

**Comment by DI555** [comment]
@nikitasius , yep , ik about tg inner build number... but i was talking about a hint/lifehack ;)... if we will have a one number we can install prev. versions over existent !!!

the same effect i suppose could be with no build number!!!
i see it in last telegraher build !!!
could we use it constantly ? i mean "no buld number" ?
(description will use of course, just to treck bulds)

**Comment by DI555** [comment]
@nikitasius , yep , ik about tg inner build number... but i was talking about a hint/lifehack ;)... if we will have a one number we can install prev. versions over existent !!!

the same effect i suppose could be with no build number!!!
i see it in last telegraher build !!!
could we use it constantly ? i mean "no buld number" ?
(description will use of course, just to treck bulds)
