### ISSUE TITLE
Feature: Read Only Mode

### ISSUE THREAD

**Issue by NSTAdventure** [nikitasius/Telegraher#77]
problem:
user should and surely want to avoid accidentally chatting on the group
(specially strict group)
because if you accidentally break the rule you may get warning or ban

solution:
add new feature called read only mode for self

If read only mode enabled you still can view the respective group but you cannot:
1. Talking on the group
2. Manage your own message
(Manage = edit / delete)
3. Replying and react user message
4.  Forward your message to where you enable this on respective group
5. blue texting where you can't use command by manually or press the blue text msg by anyone on group

FAQ:
1. do not join on strict group what's problem?
- the group may usefull for you sometime you will need them

2. turn off your phone ok?
- no that's called nuts 🗿
(bruh 🗿🗿🗿🗿)

Other notes:
Pls also expand the feature by allow user to enable / disable read only mode to specific group and add time management so feature will enabled or disabled specifically or not for xxx time
and also pls make this ability available on dm too with same feature and extending

**Comment by nikitasius** [comment]
i prefer to ban you in chat :moyai:

**Comment by ghost** [comment]
> i prefer to ban you in chat 🗿

No please! 🥺
am innocent :-(

Edit:
Also pls still considered my idea for final time it can help you to [control yourself better](https://t.me/tgbetachat/1460712)

After this yes i stop suggest same thing i don't want get cut off from all your graher network 💀
@nikitasius
