### ISSUE TITLE
Предложение пересылка

### ISSUE THREAD

**Issue by Godchac** [nikitasius/Telegraher#79]
- Пересылка с возможностью редактирования сообщений, текста к файлам
- время и дата на пересланом сообщений когда оно было написано (очень полезно, чтобы не заходить в канал и смотреть дату публикации,а иногда и нельзя так как канал закрыт или это личное сообщение

P/s первое к второму не как не относится,это две идей, и такие функции мне нужны и другим думаю тоже

**Comment by Godchac** [comment]
Также было бы неплохо добавить автоматический переводчик сообщений или хотябы кнопку перевода рядом с сообщениям

**Comment by MelonHell** [comment]
ещё было бы круто добавить возможность пересылки без автора, как PlusMessenger

**Comment by nikitasius** [comment]
> время и дата на пересланом сообщений когда оно было написано (очень полезно, чтобы не заходить в канал и смотреть дату публикации,а иногда и нельзя так как канал закрыт или это личное сообщение

уже есть.

> Также было бы неплохо добавить автоматический переводчик сообщений или хотябы кнопку перевода рядом с сообщениям

автоматике нет, а выбору языка да (чтобы язык можно было выбрать, а не автоматом на локаль клиента).

> ещё было бы круто добавить возможность пересылки без автора, как PlusMessenger

есть в ванилле уже 100500 лет.
